# Generated by Django 2.2.18 on 2021-04-01 23:10

import blacklist.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='expire',
            field=models.DateTimeField(default=blacklist.models.oneyear),
        ),
        migrations.AlterField(
            model_name='rule',
            name='duration',
            field=models.DurationField(default=blacklist.models.zeroduration, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
    ]
